export enum BUTTON_TYPE {
  CIRCLE_SUBMIT = 'CIRCLE_SUBMIT',
  CIRCLE_CANCEL = 'CIRCLE_CANCEL',
  CIRCLE_RESET = 'CIRCLE_RESET',
  CIRCLE_DELETED = 'CIRCLE_DELETED',
  CIRCLE_DUPLICATE = 'CIRCLE_DUPLICATE',
  CIRCLE_EDIT = 'CIRCLE_EDIT',

  SQUARE_SUBMIT = 'SQUARE_SUBMIT',
  SQUARE_CANCEL = 'SQUARE_CANCEL',
  SQUARE_RESET = 'SQUARE_RESET',
  SQUARE_DELETED = 'SQUARE_DELETED',
  SQUARE_DUPLICATE = 'SQUARE_DUPLICATE',
  SQUARE_EDIT = 'SQUARE_EDIT',

  LOADING = 'LOADING',
}

export const BUTTON_CLASS = {
  [BUTTON_TYPE.CIRCLE_SUBMIT]: 'btn btn-pc5',
  [BUTTON_TYPE.CIRCLE_CANCEL]: 'btn btn-secondary',
  [BUTTON_TYPE.CIRCLE_RESET]: 'btn btn btn-pc2',
  [BUTTON_TYPE.CIRCLE_DELETED]: 'btn btn-pc4',
  [BUTTON_TYPE.CIRCLE_DUPLICATE]: 'btn btn-pc5',
  [BUTTON_TYPE.CIRCLE_EDIT]: 'btn btn-pc1',

  [BUTTON_TYPE.SQUARE_SUBMIT]: 'btn btn-pc5 btn-sm',
  [BUTTON_TYPE.SQUARE_CANCEL]: 'btn btn-secondary btn-sm',
  [BUTTON_TYPE.SQUARE_RESET]: 'btn btn btn-pc2 btn-sm',
  [BUTTON_TYPE.SQUARE_DELETED]: 'btn btn-pc4 btn-sm',
  [BUTTON_TYPE.SQUARE_DUPLICATE]: 'btn btn-pc5 btn-sm',
  [BUTTON_TYPE.SQUARE_EDIT]: 'btn btn-pc8 btn-sm',

  [BUTTON_TYPE.LOADING]: 'btn spinner-border spinner-border-sm',
};
